In [2]:
import pandas as pd
import numpy as np

In [3]:
insert = pd.read_csv(r'clean.csv')
insert

,DateTime,NOx,NO2,NO,SiteID,PM10,NVPM10,VPM10,NVPM2.5,PM2.5,...,SO2,Temperature,RH,Air Pressure,Location,geo_point_2d,DateStart,DateEnd,Current,Instrument Type
0,2019-04-29 23:00:00+00:00,122.250000,49.250000,47.750000,501,30.400000,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Colston Avenue,"51.455269382758324, -2.596648828557916",2018-11-30T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
1,2019-04-30 03:00:00+00:00,42.250000,35.250000,4.500000,501,20.275000,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Colston Avenue,"51.455269382758324, -2.596648828557916",2018-11-30T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
2,2019-05-01 06:00:00+00:00,82.000000,48.500000,21.750000,501,28.125000,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Colston Avenue,"51.455269382758324, -2.596648828557916",2018-11-30T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
3,2019-05-01 18:00:00+00:00,357.250000,117.750000,156.500000,501,27.700000,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Colston Avenue,"51.455269382758324, -2.596648828557916",2018-11-30T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
4,2019-05-02 14:00:00+00:00,194.500000,73.250000,79.250000,501,23.775000,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Colston Avenue,"51.455269382758324, -2.596648828557916",2018-11-30T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881535,2023-02-07 12:00:00+00:00,310.749908,79.097813,151.033870,501,18.570911,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Colston Avenue,"51.455269382758324, -2.596648828557916",2018-11-30T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
881536,2023-02-07 12:00:00+00:00,157.616566,63.008375,61.702946,463,18.570911,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Fishponds Road,"51.47804497171107, -2.535230274543903",2009-03-13T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
881537,2023-02-07 12:00:00+00:00,228.622528,62.537157,108.474798,672,18.570911,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Marlborough Street,"51.45914197176008, -2.595432718360466",2021-07-01T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
881538,2023-02-07 14:00:00+00:00,198.958434,75.485843,80.472720,463,18.570911,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Fishponds Road,"51.47804497171107, -2.535230274543903",2009-03-13T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
881539,2023-02-07 13:00:00+00:00,103.990594,47.646219,36.737659,203,18.570911,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Brislington Depot,"51.441747180510106, -2.5599558321904605",2001-01-01T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference

In [4]:
insert_subset = insert.head(100)
insert_subset

,DateTime,NOx,NO2,NO,SiteID,PM10,NVPM10,VPM10,NVPM2.5,PM2.5,...,SO2,Temperature,RH,Air Pressure,Location,geo_point_2d,DateStart,DateEnd,Current,Instrument Type
0,2019-04-29 23:00:00+00:00,122.25,49.25,47.75,501,30.400,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Colston Avenue,"51.455269382758324, -2.596648828557916",2018-11-30T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
1,2019-04-30 03:00:00+00:00,42.25,35.25,4.50,501,20.275,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Colston Avenue,"51.455269382758324, -2.596648828557916",2018-11-30T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
2,2019-05-01 06:00:00+00:00,82.00,48.50,21.75,501,28.125,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Colston Avenue,"51.455269382758324, -2.596648828557916",2018-11-30T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
3,2019-05-01 18:00:00+00:00,357.25,117.75,156.50,501,27.700,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Colston Avenue,"51.455269382758324, -2.596648828557916",2018-11-30T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
4,2019-05-02 14:00:00+00:00,194.50,73.25,79.25,501,23.775,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Colston Avenue,"51.455269382758324, -2.596648828557916",2018-11-30T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2019-05-30 17:00:00+00:00,152.75,54.25,64.25,501,15.700,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Colston Avenue,"51.455269382758324, -2.596648828557916",2018-11-30T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
96,2019-05-30 18:00:00+00:00,184.75,73.75,72.75,501,16.125,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Colston Avenue,"51.455269382758324, -2.596648828557916",2018-11-30T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
97,2019-05-31 05:00:00+00:00,32.00,12.00,12.75,501,11.375,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Colston Avenue,"51.455269382758324, -2.596648828557916",2018-11-30T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
98,2019-05-31 06:00:00+00:00,73.75,25.75,31.00,501,8.700,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Colston Avenue,"51.455269382758324, -2.596648828557916",2018-11-30T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference
99,2019-05-31 13:00:00+00:00,288.00,80.50,135.25,501,22.500,13.975167,3.445466,9.139141,11.522119,...,1.758152,9.489511,18.555307,DefaultValue,Colston Avenue,"51.455269382758324, -2.596648828557916",2018-11-30T00:00:00+00:00,2015-12-31T00:00:00+00:00,True,Continuous Reference

In [5]:
insert_subset.to_csv('cropped_clean.csv', sep=',', index=False)